import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[bell]
animation = "EaseOutExpo"

[cursor.style]
shape = "Beam"

[font]
size = 12.0

[font.normal]
family = "Fira Code Nerd Font Mono"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex =  "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
opacity = 1
startup_mode = "Fullscreen"
